# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Setup
title:            'Eleftheria (Ria) Kotti'
tagline:          ''
description:      ''
url:              riakotti.github.io 
baseurl:          /

author:
  name:           'Eleftheria Kotti'
  url:
  email:          'elefteriak@hotmail.com'
  image:          'me.jpg'


paginate:         0



